import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F5F7FA",
    },
    header: {
      backgroundColor: "#1E5F74",
      paddingTop: 50,
      paddingBottom: 15,
      paddingHorizontal: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      elevation: 4,
    },
    headerTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#FFFFFF",
      marginTop: 10,
    },
    backButton: {
      flexDirection: "row",
      alignItems: "center",
    },
    backButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      marginLeft: 8,
    },
    tabContainer: {
      flexDirection: "row",
      backgroundColor: "#FFFFFF",
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginTop: 15,
      marginHorizontal: 15,
      borderRadius: 10,
      elevation: 2,
    },
    tab: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginRight: 8,
      borderRadius: 20,
    },
    activeTab: {
      backgroundColor: "#1E5F74",
    },
    tabText: {
      color: "#666",
      fontSize: 14,
      fontWeight: "500",
    },
    activeTabText: {
      color: "#fff",
      fontWeight: "bold",
    },
    contentContainer: {
      flex: 1,
    },
    content: {
      padding: 16,
    },
    statsContainer: {
      padding: 16,
    },
    statsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 16,
    },
    statsCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      padding: 16,
      width: "48%",
      alignItems: "center",
      elevation: 2,
    },
    statsNumber: {
      fontSize: 32,
      fontWeight: "bold",
      color: "#1E5F74",
      marginBottom: 8,
    },
    statsLabel: {
      fontSize: 14,
      color: "#666",
      textAlign: "center",
    },
    infoCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      elevation: 2,
    },
    detailRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    detailLabel: {
      color: "#666",
      width: 120,
      fontSize: 15,
      fontWeight: "500",
      marginLeft: 10,
    },
    detailText: {
      color: "#333",
      flex: 1,
      fontSize: 15,
    },
    statusBadge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    statusText: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "bold",
    },
    descriptionCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      elevation: 2,
    },
    descriptionLabel: {
      color: "#666",
      fontSize: 15,
      fontWeight: "500",
      marginBottom: 10,
    },
    descriptionText: {
      color: "#333",
      fontSize: 15,
      lineHeight: 22,
    },
    addTaskButton: {
      backgroundColor: "#FF6B6B",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      marginTop: 16,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
      elevation: 4,
    },
    addTaskButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 8,
    },
    viewTasksButton: {
      backgroundColor: "#1E5F74",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      marginTop: 12,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
      elevation: 4,
    },
    viewTasksButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 8,
    },
    materialsButton: {
      backgroundColor: "#1E5F74",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      marginTop: 12,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
      elevation: 4,
    },
    materialsButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 8,
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      padding: 10,
      paddingTop: 80,
    },
    modalContent: {
      backgroundColor: "#FFFFFF",
      borderRadius: 15,
      padding: 20,
      width: 400,
      maxWidth: 700,
      elevation: 5,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#333",
    },
    inputGroup: {
      marginBottom: 16,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "bold",
      color: "#555",
      marginBottom: 6,
    },
    helperText: {
      fontSize: 12,
      color: "#888",
      marginTop: 4,
      fontStyle: "italic",
    },
    input: {
      backgroundColor: "#F9F9F9",
      borderWidth: 1,
      borderColor: "#E0E0E0",
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: "#333",
    },
    textArea: {
      height: 100,
      textAlignVertical: "top",
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 20,
    },
    modalButton: {
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
    },
    cancelButton: {
      backgroundColor: "#F0F0F0",
      marginRight: 10,
    },
    cancelButtonText: {
      color: "#666",
      fontWeight: "bold",
      fontSize: 16,
    },
    saveButton: {
      backgroundColor: "#1E5F74",
      marginLeft: 10,
    },
    saveButtonText: {
      color: "#FFFFFF",
      fontWeight: "bold",
      fontSize: 16,
    },
    personalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    personalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#333",
    },
    inviteButton: {
      backgroundColor: "#1E5F74",
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      flexDirection: "row",
      alignItems: "center",
    },
    inviteButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "500",
      marginLeft: 6,
    },
    rolSection: {
      marginBottom: 20,
    },
    rolTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#666",
      marginBottom: 10,
      paddingLeft: 8,
    },
    miembroCard: {
      backgroundColor: "#FFFFFF",
      padding: 16,
      borderRadius: 10,
      marginBottom: 12,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      elevation: 2,
    },
    miembroInfo: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
    },
    miembroAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#1E5F74",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    miembroAvatarText: {
      color: "#FFFFFF",
      fontSize: 18,
      fontWeight: "bold",
    },
    miembroDetails: {
      flex: 1,
    },
    miembroNombre: {
      fontSize: 16,
      color: "#333",
      fontWeight: "500",
      marginBottom: 4,
    },
    miembroEmail: {
      fontSize: 14,
      color: "#666",
    },
    eliminarButton: {
      backgroundColor: "#FF6B6B",
      padding: 8,
      borderRadius: 8,
    },
    finalizarButton: {
      backgroundColor: "#FF6B6B",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 30,
      marginTop: 16,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
      elevation: 4,
    },
    finalizarButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 8,
    },
    rolSelector: {
      marginTop: 8,
    },
    rolOption: {
      backgroundColor: "#F9F9F9",
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
    },
    rolOptionSelected: {
      backgroundColor: "#1E5F74",
    },
    rolOptionText: {
      color: "#333",
      fontSize: 16,
    },
    rolOptionTextSelected: {
      color: "#FFFFFF",
      fontWeight: "bold",
    },
    searchResults: {
      backgroundColor: "#F9F9F9",
      borderRadius: 8,
      marginTop: 4,
      maxHeight: 150,
    },
    searchResultItem: {
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#E0E0E0",
      flexDirection: "row",
      alignItems: "center",
    },
    searchResultAvatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: "#1E5F74",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    searchResultAvatarText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "bold",
    },
    searchResultInfo: {
      flex: 1,
    },
    searchResultText: {
      color: "#333",
      fontSize: 15,
      fontWeight: "500",
    },
    searchResultSubtext: {
      color: "#666",
      fontSize: 13,
      marginTop: 2,
    },
    selectedMemberContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F9F9F9",
      padding: 12,
      borderRadius: 8,
      marginTop: 8,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    selectedMemberAvatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: "#1E5F74",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    selectedMemberAvatarText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "bold",
    },
    selectedMemberText: {
      color: "#333",
      fontSize: 15,
      flex: 1,
    },
    removeMemberButton: {
      padding: 5,
    },
    prioridadContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 8,
    },
    prioridadOption: {
      flex: 1,
      padding: 12,
      borderRadius: 8,
      marginHorizontal: 4,
      alignItems: "center",
      borderWidth: 1,
    },
    prioridadText: {
      fontSize: 14,
      fontWeight: "500",
    },
    miembroProfileImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
    },
    searchResultProfileImage: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
    selectedMemberProfileImage: {
      width: 30,
      height: 30,
      borderRadius: 15,
    },
    // Estilos para el componente de clima
    weatherCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      padding: 16,
      marginTop: 20,
      elevation: 2,
    },
    weatherHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    weatherTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
    },
    weatherIcon: {
      width: 50,
      height: 50,
    },
    weatherDetails: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 16,
    },
    weatherDetail: {
      flexDirection: "row",
      alignItems: "center",
    },
    weatherDetailText: {
      fontSize: 16,
      color: "#333",
      marginLeft: 6,
    },
    constructionStatus: {
      flexDirection: "row",
      alignItems: "center",
      padding: 12,
      borderRadius: 8,
      justifyContent: "center",
    },
    constructionStatusText: {
      color: "#FFFFFF",
      fontSize: 14,
      fontWeight: "bold",
      marginLeft: 8,
    },
    weatherLoadingText: {
      color: "#666",
      fontSize: 14,
      marginTop: 8,
      textAlign: "center",
    },
    weatherErrorText: {
      color: "#FF6B6B",
      fontSize: 14,
      marginTop: 8,
      textAlign: "center",
    },
    // Estilos para el componente de porcentaje de cumplimiento
    completionCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      padding: 16,
      marginTop: 16,
      elevation: 2,
    },
    completionTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 12,
    },
    progressBarContainer: {
      height: 12,
      backgroundColor: "#F0F0F0",
      borderRadius: 6,
      overflow: "hidden",
      marginBottom: 8,
    },
    progressBar: {
      height: "100%",
      backgroundColor: "#4CAF50",
      borderRadius: 6,
    },
    percentageText: {
      fontSize: 14,
      fontWeight: "bold",
      color: "#333",
      textAlign: "center",
    },
    // Estilos para administrar materiales
    selectedMaterialContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#F9F9F9",
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
    },
    selectedMaterialText: {
      color: "#333",
      fontSize: 15,
      flex: 1,
    },
    cantidadContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    cantidadLabel: {
      color: "#666",
      fontSize: 14,
      marginRight: 4,
    },
    cantidadInput: {
      backgroundColor: "#FFFFFF",
      borderWidth: 1,
      borderColor: "#E0E0E0",
      borderRadius: 8,
      padding: 8,
      fontSize: 14,
      color: "#333",
      width: 60,
      textAlign: "center",
      marginHorizontal: 4,
    },
    unidadText: {
      color: "#666",
      fontSize: 14,
      marginLeft: 4,
    },
    // Estilos para la nueva interfaz de administración de materiales
    materialsTabContainer: {
      flexDirection: "row",
      marginBottom: 16,
      borderRadius: 8,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    materialsTab: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      flex: 1,
      alignItems: "center",
    },
    materialsTabText: {
      fontSize: 14,
      fontWeight: "bold",
    },
    materialsList: {
      maxHeight: 300,
      marginBottom: 16,
    },
    materialItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#FFFFFF",
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
    },
    materialInfo: {
      flex: 1,
    },
    materialName: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
    },
    materialDescription: {
      fontSize: 14,
      color: "#666",
    },
    materialStock: {
      alignItems: "flex-end",
    },
    materialQuantity: {
      fontSize: 15,
      color: "#333",
      marginBottom: 4,
    },
    materialActions: {
      flexDirection: "row",
    },
    materialActionButton: {
      backgroundColor: "#F0F0F0",
      padding: 6,
      borderRadius: 6,
      marginLeft: 4,
    },
    emptyMaterialsContainer: {
      alignItems: "center",
      padding: 20,
    },
    emptyMaterialsText: {
      fontSize: 16,
      color: "#BBBBBB",
      marginTop: 10,
    },
    addMaterialForm: {
      marginBottom: 16,
    },
    inputRow: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    addMaterialButton: {
      backgroundColor: "#4CAF50",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "center",
    },
    addMaterialButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 8,
    },
    // Estilos para los materiales seleccionados en la tarea
    selectedMaterialsContainer: {
      marginBottom: 16,
    },
    selectedMaterialItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#F9F9F9",
      padding: 12,
      borderRadius: 8,
      marginBottom: 8,
    },
    selectedMaterialInfo: {
      flex: 1,
    },
    selectedMaterialName: {
      fontSize: 15,
      fontWeight: "500",
      color: "#333",
    },
    selectedMaterialStock: {
      fontSize: 13,
      color: "#666",
    },
    selectedMaterialQuantity: {
      flexDirection: "row",
      alignItems: "center",
    },
    quantityInput: {
      backgroundColor: "#FFFFFF",
      borderWidth: 1,
      borderColor: "#E0E0E0",
      borderRadius: 8,
      padding: 8,
      fontSize: 14,
      color: "#333",
      width: 50,
      textAlign: "center",
      marginRight: 4,
    },
    quantityUnit: {
      fontSize: 14,
      color: "#666",
    },
    removeMaterialButton: {
      padding: 5,
    },
    noMaterialsText: {
      fontSize: 14,
      color: "#666",
      fontStyle: "italic",
    },
    searchMaterialContainer: {
      marginTop: 8,
    },
    outOfStockItem: {
      opacity: 0.5,
    },
    outOfStockText: {
      fontSize: 12,
      color: "#FF6B6B",
      marginLeft: 8,
    },
    // Estilos adicionales para la sección de inventario en el modal de materiales
    inventarioSection: {
      flex: 1,
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F9F9F9",
      borderRadius: 8,
      paddingHorizontal: 12,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    searchIcon: {
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
      color: "#333",
      paddingVertical: 12,
    },
    inputError: {
      borderColor: "#FF6B6B",
      borderWidth: 1,
    },
    errorText: {
      color: "#FF6B6B",
      fontSize: 12,
      marginTop: 4,
    },
    helperText: {
      color: "#888",
      fontSize: 12,
      marginTop: 4,
      fontStyle: "italic",
    },
    // Estilos mejorados para el modal de materiales
    materialItemCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 8,
      padding: 12,
      marginBottom: 10,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    materialActions: {
      flexDirection: "row",
      alignItems: "center",
    },
    deleteMaterialButton: {
      padding: 8,
      borderRadius: 4,
      marginLeft: 10,
    },
    progressContainer: {
      marginVertical: 15,
      paddingHorizontal: 5,
    },
    progressBar: {
      height: 10,
      backgroundColor: "#E0E0E0",
      borderRadius: 5,
      marginBottom: 5,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      backgroundColor: "#1E5F74",
      borderRadius: 5,
    },
    progressText: {
      fontSize: 12,
      color: "#666",
      textAlign: "right",
    }
  })
  
  