import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F7FA",
  },
  header: {
    backgroundColor: "#1E5F74",
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 4,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    marginLeft: 8,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginTop: 10,
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 15,
    marginHorizontal: 15,
    borderRadius: 10,
    elevation: 2,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActivo: {
    borderBottomColor: "#1E5F74",
  },
  tabText: {
    color: "#666",
    fontSize: 14,
    fontWeight: "500",
  },
  tabTextoActivo: {
    color: "#1E5F74",
    fontWeight: "bold",
  },
  filtrosHeader: {
    padding: 16,
  },
  filtrosBoton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: 10,
    borderRadius: 8,
    alignSelf: "flex-start",
    elevation: 2,
  },
  filtrosBotonTexto: {
    color: "#1E5F74",
    marginLeft: 8,
    fontSize: 14,
    fontWeight: "500",
  },
  filtrosBadge: {
    backgroundColor: "#FF6B6B",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  filtrosBadgeTexto: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
    paddingHorizontal: 6,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    minHeight: "60%",
    maxHeight: "90%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  closeButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F5F5F5",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
  },
  filtroSeccion: {
    marginBottom: 20,
  },
  filtroTituloContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  filtroTitulo: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#555",
    marginLeft: 8,
  },
  filtroOpciones: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filtroOpcion: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F9F9F9",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  filtroOpcionTexto: {
    color: "#333",
    fontSize: 14,
    fontWeight: "500",
  },
  modalBotones: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  modalBoton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  modalBotonPrimario: {
    backgroundColor: "#1E5F74",
    marginLeft: 10,
  },
  modalBotonSecundario: {
    backgroundColor: "#F0F0F0",
    marginRight: 10,
  },
  modalBotonTextoPrimario: {
    color: "#fff",
    fontWeight: "600",
  },
  modalBotonTextoSecundario: {
    color: "#666",
    fontWeight: "600",
  },
  seccion: {
    marginBottom: 24,
  },
  tareaCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
    elevation: 2,
  },
  tareaTitulo: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  tareaDescripcion: {
    fontSize: 14,
    color: "#555",
    marginBottom: 12,
  },
  tareaDetalles: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  tareaDetalleItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  tareaAsignado: {
    fontSize: 14,
    color: "#555",
    marginLeft: 6,
  },
  tareaFecha: {
    fontSize: 14,
    color: "#555",
    marginLeft: 6,
  },
  tareaEstadoContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 8,
  },
  prioridadBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  prioridadText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  estadoBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  estadoText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
    padding: 20,
  },
  emptyMessage: {
    color: "#666",
    fontSize: 16,
    textAlign: "center",
    marginTop: 10,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    borderRadius: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#333",
    fontSize: 16,
    paddingVertical: 12,
  },
  resultadosBusqueda: {
    marginTop: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    elevation: 2,
    maxHeight: 200,
  },
  resultadoBusqueda: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  resultadoAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#1E5F74",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  resultadoAvatarText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  resultadoInfo: {
    flex: 1,
  },
  resultadoNombre: {
    fontSize: 14,
    fontWeight: "500",
    color: "#333",
  },
  resultadoRol: {
    fontSize: 12,
    color: "#666",
  },
  noResultadosContainer: {
    alignItems: "center",
    padding: 20,
  },
  noResultados: {
    color: "#666",
    fontSize: 14,
    textAlign: "center",
    fontStyle: "italic",
    marginTop: 8,
  },
  // Estilos para el modal de detalles
  detallesModalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "90%",
    minHeight: "60%",
  },
  detallesTitulo: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    flex: 1,
  },
  cerrarBoton: {
    padding: 8,
  },
  detallesScroll: {
    flex: 1,
  },
  detallesSubtitulo: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginTop: 16,
    marginBottom: 8,
  },
  detallesDescripcion: {
    fontSize: 16,
    color: "#555",
    marginBottom: 16,
    lineHeight: 24,
  },
  detallesInfoContainer: {
    marginTop: 16,
  },
  detallesInfoItem: {
    marginBottom: 16,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  detallesInfoLabel: {
    fontSize: 14,
    color: "#666",
    marginLeft: 8,
  },
  detallesInfoValor: {
    fontSize: 16,
    color: "#333",
    marginTop: 4,
  },
  textoVencido: {
    color: "#FF6B6B",
    fontWeight: "bold",
  },
  textoProximoVencer: {
    color: "#FF9800",
    fontWeight: "bold",
  },
  finalizarBoton: {
    backgroundColor: "#1E5F74",
    borderRadius: 8,
    padding: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },
  finalizarBotonTexto: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  // Estilos para el modal de finalización
  finalizarModalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  finalizarModalTitulo: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
  },
  finalizarModalSubtitulo: {
    fontSize: 16,
    color: "#666",
    marginBottom: 20,
  },
  comentarioInput: {
    backgroundColor: "#F9F9F9",
    borderRadius: 8,
    padding: 16,
    fontSize: 16,
    color: "#333",
    minHeight: 120,
    textAlignVertical: "top",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  botonDeshabilitado: {
    opacity: 0.7,
  },
  // Estilos para cambiar fecha
  fechaContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  editarFechaBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  editarFechaText: {
    color: "#1E5F74",
    fontSize: 12,
    marginLeft: 4,
    fontWeight: "500",
  },
  fechaPickerContainer: {
    marginBottom: 20,
  },
  fechaPickerLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#555",
    marginBottom: 10,
  },
  fechaInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  fechaInput: {
    flex: 1,
    color: "#333",
    fontSize: 16,
    paddingVertical: 12,
  },
  fechaErrorText: {
    color: "#FF6B6B",
    fontSize: 12,
    marginTop: 4,
  },
  fechaHelperText: {
    color: "#666",
    fontSize: 12,
    marginTop: 4,
  },
  cambiofechaItem: {
    backgroundColor: "#F9F9F9",
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  cambioFechaTexto: {
    fontSize: 14,
    color: "#555",
    marginBottom: 4,
  },
  cambioFechaLabel: {
    fontWeight: "bold",
    color: "#333",
  },
  // Estilos para la evidencia de imagen
  evidenciaContainer: {
    marginBottom: 20,
  },
  evidenciaLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#555",
    marginBottom: 10,
  },
  evidenciaBotones: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  evidenciaBoton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    padding: 12,
    borderRadius: 8,
    flex: 0.48,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  evidenciaBotonTexto: {
    color: "#1E5F74",
    marginLeft: 8,
    fontSize: 14,
    fontWeight: "500",
  },
  imagenPreviewContainer: {
    position: "relative",
    marginTop: 10,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  imagenPreview: {
    width: "100%",
    height: 200,
    borderRadius: 8,
  },
  eliminarImagenBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgb(255, 255, 255)",
    borderRadius: 20,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  evidenciaImagenContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
  },
  evidenciaImagenThumbnail: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  verImagenText: {
    color: "#1E5F74",
    fontSize: 14,
    fontWeight: "500",
    textDecorationLine: "underline",
  },
  // Estilos para previsualización de imagen a pantalla completa
  imagenAmpliadaContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgb(255, 255, 255)",
    zIndex: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  imagenAmpliada: {
    width: 300,
    height: 400,
    borderRadius: 8,
  },
  cerrarImagenAmpliadaBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 11,
  },
  // Estilos para filtros mejorados
  usuarioSeleccionadoContainer: {
    marginTop: 12,
    marginBottom: 16,
  },
  usuarioSeleccionadoLabel: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  usuarioSeleccionado: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F8FF",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1E5F74",
  },
  usuarioAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#1E5F74",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  usuarioAvatarText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  usuarioNombre: {
    flex: 1,
    fontSize: 14,
    color: "#333",
    fontWeight: "500",
  },
  eliminarUsuarioBtn: {
    padding: 5,
  },
  filtrosActivos: {
    marginTop: 10,
    marginBottom: 20,
  },
  filtrosActivosLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#555",
    marginBottom: 8,
  },
  filtrosActivosContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filtroActivoTag: {
    backgroundColor: "#1E5F74",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  filtroActivoText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
});