import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F5F7FA",
    },
    keyboardAvoidingView: {
      flex: 1,
    },
    scrollView: {
      flex: 1,
    },
    scrollViewContent: {
      paddingBottom: 100, // Extra padding to account for bottom nav
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#F5F7FA",
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: "#666",
    },
    header: {
      backgroundColor: "#1E5F74",
      paddingTop: 50,
      paddingBottom: 15,
      paddingHorizontal: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      elevation: 4,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: "bold",
      color: "#FFFFFF",
      marginTop: 10,
    },
    profileSection: {
      alignItems: "center",
      paddingVertical: 24,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
      backgroundColor: "#FFFFFF",
      marginHorizontal: 20,
      marginTop: 20,
      borderRadius: 15,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    profileImageContainer: {
      position: "relative",
      marginBottom: 16,
    },
    profileImageWrapper: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: "#F9F9F9",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderWidth: 3,
      borderColor: "#F0F0F0",
    },
    profileImage: {
      width: "100%",
      height: "100%",
      borderRadius: 60,
    },
    profileImagePlaceholder: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#F9F9F9",
    },
    uploadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    editImageButton: {
      position: "absolute",
      bottom: 0,
      right: 0,
      backgroundColor: "#FF6B6B",
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 3,
      borderColor: "#FFFFFF",
      elevation: 4,
    },
    emailText: {
      fontSize: 16,
      color: "#555",
    },
    formSection: {
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
      backgroundColor: "#FFFFFF",
      marginHorizontal: 20,
      marginTop: 20,
      borderRadius: 15,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    securitySection: {
      padding: 20,
      backgroundColor: "#FFFFFF",
      marginHorizontal: 20,
      marginTop: 20,
      borderRadius: 15,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    bottomPadding: {
      height: 80, // Extra padding at the bottom to ensure content is visible above the bottom nav
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 16,
    },
    inputGroup: {
      marginBottom: 16,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "bold",
      color: "#555",
      marginBottom: 6,
    },
    input: {
      backgroundColor: "#F9F9F9",
      borderWidth: 1,
      borderColor: "#E0E0E0",
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      color: "#333",
    },
    saveButton: {
      backgroundColor: "#1E5F74",
      borderRadius: 8,
      padding: 16,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginTop: 8,
      elevation: 2,
    },
    buttonDisabled: {
      opacity: 0.7,
    },
    buttonIcon: {
      marginRight: 8,
    },
    buttonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "bold",
    },
    securityButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: "#F9F9F9",
      borderRadius: 8,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    securityButtonText: {
      flex: 1,
      fontSize: 16,
      color: "#333",
      marginLeft: 8,
    },
    logoutButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FFF0F0",
      borderRadius: 8,
      padding: 16,
      marginTop: 8,
      borderWidth: 1,
      borderColor: "#FFE0E0",
    },
    logoutButtonText: {
      fontSize: 16,
      color: "#FF3B30",
      fontWeight: "bold",
      marginLeft: 8,
    },
    modal: {
      justifyContent: "flex-end",
      margin: 0,
    },
    modalContent: {
      backgroundColor: "#FFFFFF",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
      paddingBottom: 36,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#333",
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 24,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: "#F0F0F0",
      borderRadius: 8,
      padding: 16,
      alignItems: "center",
      marginRight: 10,
    },
    cancelButtonText: {
      color: "#666",
      fontWeight: "bold",
      fontSize: 16,
    },
    changePasswordButton: {
      flex: 1,
      backgroundColor: "#1E5F74",
      borderRadius: 8,
      padding: 16,
      alignItems: "center",
      marginLeft: 10,
    },
    changePasswordButtonText: {
      color: "#FFFFFF",
      fontWeight: "bold",
      fontSize: 16,
    },
    imageOptionsContent: {
      backgroundColor: "#FFFFFF",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
    },
    imageOptionsTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 20,
      textAlign: "center",
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    imageOption: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      borderRadius: 8,
      backgroundColor: "#F9F9F9",
      marginBottom: 12,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    imageOptionIcon: {
      marginRight: 12,
    },
    imageOptionText: {
      fontSize: 16,
      color: "#333",
    },
    cancelImageOption: {
      padding: 16,
      borderRadius: 8,
      backgroundColor: "#F0F0F0",
      marginTop: 8,
      alignItems: "center",
    },
    cancelImageOptionText: {
      fontSize: 16,
      color: "#FF3B30",
      fontWeight: "bold",
    },
  })
  
  